name: Generate Pacman

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # Allows to manually run the job at any time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-pacman

    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Pacman
        uses: k2d222/pacman-github-contribution@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
